version: "3.8"

services:
  app:
    container_name: balanced-starter-dev
    image: balanced-starter-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
